Clean up LinuxDonTest

diff --git a/scripts/sosp15/LinuxDonTest b/scripts/sosp15/LinuxDonTest
--- a/scripts/sosp15/LinuxDonTest
+++ b/scripts/sosp15/LinuxDonTest
@@ -1,27 +1,27 @@
 #!/bin/bash
 set -x
 
-# THIS EXPERIMENT
-DONEXPDIR=/home/don/kh/experiment/memcached_linux
-APP_NAME=vmlinuz-3.15.0-4-amd64
-INITD_NAME=memcached_3-13.cgz
-APP_PATH=/home/jmcadden/work/SOSP/imgs/${APP_NAME}
-INITD_PATH=/home/jmcadden/work/SOSP/imgs/${INITD_NAME}
-QEMU_APPEND="quiet console=ttyS0 ro 1"
+# MEMCACHED 
+MCDSERVER=${MCD_SERVER:-192.168.4.104}
+MCDOPTIONS=${MCD_OPTIONS:-"RUNTIME=1200 MPOINTS=10 EPOINTS=2"}
 
-# MISC
-EXPNAME="Linux"
+# THIS EXPERIMENT
+EXPNAME=${EXP_NAME:-"Linux"}
+DONEXPDIR=/home/don/kh/experiment/memcached_linux
+APP_NAME=vmlinuz-3.16.0-4-amd64
+INITD_NAME=memcached_3-13.cgz
+APP_PATH=/home/jmcadden/work/SOSP15/imgs/${APP_NAME}
+INITD_PATH=/home/jmcadden/work/SOSP15/imgs/${INITD_NAME}
 EBBRT_REPO=
 APP_REPO=
+EXPBUILD=${EXP_BUILD:-}
+EXPMONITOR=${EXP_MONITOR:-}
 
-# QEMU TYPE {qemu1core, qemu4core, qemu6core}
+# QEMU {qemu1core, qemu4core, qemu6core}
 QEMU_ALLOC=${QEMU_ALLOC:-qemu4core}
+QEMUAPPEND=${QEMU_APPEND:-"quiet console=ttyS0 ro 1"}
 
-# MEMCACHED 
-MCD_SERVER=192.168.4.104
-MCD_OPTIONS="RUNTIME=1200 MPOINTS=10 EPOINTS=2"
-
-# EXPERIMENT 
+# EXPERIMENT INTERNALS
 BOOTFILE=${DONEXPDIR}/boot
 STARTFILE=${DONEXPDIR}/start
 STOPFILE=${DONEXPDIR}/stop
@@ -51,6 +51,12 @@ EOF
 
 function mkExpStart()
 {
+  if [[ -n $INITD_NAME ]]; then
+    INITRD="\$APPDIR/$INITD_NAME"
+  else
+    INITRD="/dev/null"
+  fi
+
     cat > $STARTFILE <<EOF
 #!/bin/bash
 set -x
@@ -59,10 +65,10 @@ RUNDIR=\$MYDIR/run
 APPDIR=\$MYDIR/files
 SCPDIR=\$MYDIR/scripts
 kernel=\$APPDIR/$APP_NAME
-initrd=\$APPDIR/$INITD_NAME
-append="${QEMU_APPEND}"
+initrd=$INITRD
+append="${QEMUAPPEND}"
 
-\$SCPDIR/$QEMU_ALLOC \$RUNDIR \$kernel \$initrd \$append
+\$SCPDIR/$QEMU_ALLOC \$RUNDIR \$kernel \$initrd "\${append}"
 
 EOF
  chmod +x $STARTFILE
@@ -71,12 +77,31 @@ EOF
 function startExp()
 {
   ssh -f don "/opt/kexec-to-kh"
-  sleep 60
+  sleep 120
   ssh nod "mkdir -p ~/mutilate-exp/$TS" > /dev/null
-  ssh -f nod "${MCD_OPTIONS} ~/mutilate-exp/batch-run ${EXPNAME}-${QEMU_ALLOC}\
+  ssh -f nod "${MCDOPTIONS} ~/mutilate-exp/batch-run ${EXPNAME}-${QEMU_ALLOC}\
 > ~/mutilate-exp/$TS/${EXPNAME}-${QEMU_ALLOC} \
 && scp -r ~/mutilate-exp/$TS kd:RESULTS "
 
+}
+
+function stopExp()
+{
+  echo "Results gathered. Shutting down experiment"
+  echo "" > /dev/ttyS0
+  sleep 2
+  echo "/etc/init.d/don_experiment stop" > /dev/ttyS0
+  sleep 120
+  echo "/bin/kexec-to-don" > /dev/ttyS0
+  sleep 60
+}
+
+function mkExpStop()
+{
+    cat > $STOPFILE <<EOF
+#!/bin/bash
+EOF
+  chmod +x $STOPFILE
 }
 
 function acquireExpLock()
@@ -90,6 +115,8 @@ function acquireExpLock()
 function releaseExpLock()
 {
   screen -X -S $SESSION quit
+  # give screen time to clean up
+  sleep 10
 }
 
 function setExp()
@@ -106,69 +133,67 @@ function mkDonDir()
   ! mkdir $DONEXPDIR && echo "ERROR: mkdir $DONEXPDIR" && exit -1
 }
 
-function mkExpStop()
-{
-    cat > $STOPFILE <<EOF
-#!/bin/bash
-EOF
-  chmod +x $STOPFILE
-}
-
 function copyFiles()
 {
    [[ -a $DONEXPDIR/files ]] && rm -rf $DONEXPDIR/files
    mkdir $DONEXPDIR/files
    cp -aL -t $DONEXPDIR/files $APP_PATH
-}
-
-function copyOutputs()
-{
-  cp $RUNDIR/*.out .
+   if [[ -n $INITD_PATH ]]; then
+     cp -aL -t $DONEXPDIR/files $INITD_PATH
+   fi
 }
 
 function expWait()
 {
+  # poll on results file uploaded from nod
   while [[ ! -a ${HOME}/RESULTS/${TS}/${EXPNAME}-${QEMU_ALLOC} ]]; do 
     sleep 10
   done
-  echo "Results gathered. Shutting down experiment"
-  echo "/bin/end-experiment" > /dev/ttyS0
 }
 
+
 #####################################
-#  RUN CODE
+#  Start`
 #####################################
 
-if [[ -n $BUILD ]]; then
-  echo $BUILD
-  echo "pulling latest version of $APP"
-  ( cd $EBBRT_REPO; git pull )
-  ( cd $APP_REPO; git pull )
-  echo "making $APP"
+if [[ -n $EXPBUILD ]]; then
+  echo "pulling latest version of $APP_NAME"
+  if [[ -n $EBBRT_REPO ]]; then
+    ( cd $EBBRT_REPO; git pull )
+  fi
+  if [[ -n $APP_REPO ]]; then
+    ( cd $APP_REPO; git pull )
+  fi
+  echo "making $APP_NAME"
   ( EBBRT_SRCDIR=$EBBRT_REPO make clean -C $APP_REPO )
   ( EBBRT_SRCDIR=$EBBRT_REPO make -j8 -C $APP_REPO )
 fi
 
 if [[ ! -a $APP_PATH ]]; then
-  echo "FAILED to locate ${APP}"
+  echo "FAILED to locate ${APP_PATH}"
+  exit -1
+fi
+if [[ -n $INID_PATH && ! -n $INIT_PATH ]]; then
+  echo "FAILED to locate ${INIT_PATH}"
   exit -1
 fi
 
-releaseExpLock
+#releaseExpLock
+
 if ! acquireExpLock; then
   echo "FAILED TO GET LOCK ON DON"
   exit -1
 fi
 
-if [[ -n $EXP_MONITOR ]]; then 
+if [[ -n $EXPMONITOR ]]; then 
    xterm -e "screen -r $SESSION" &
 fi
 
-while ! ping -c1 don &>/dev/null; do 
+if ! ping -c1 don &>/dev/null; then 
   echo "Don is not in native boot"; 
   releaseExpLock
   exit -1
-done
+fi
 
 mkDonDir
 copyFiles
@@ -177,10 +202,11 @@ mkExpStart
 mkExpStop
 mkExpLinks
 setExp
+
+echo "Experiment Started: $(date)"
 startExp
 expWait
+stopExp
 releaseExpLock
-#copyOutputs
-
-echo "Experiment Finished."
+echo "Experiment Finished: $(date)"
 
